import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Generates the DSpace SAF packages the seed imports, from tools/dspace/catalog.json.
 *
 * Breadth is a property of the data table, not of the repository tree. Committing one directory
 * per item would mean hundreds of near-identical XML files whose only differences are a state name
 * and a FIPS code, and changing the program mix would mean regenerating all of them by hand. The
 * table is the committed source of truth; the packages below it are build output and git-ignored.
 *
 * Usage:
 *   node tools/scripts/generate-saf.mjs            regenerate every enabled program
 *   node tools/scripts/generate-saf.mjs --areas 5  first N areas only, for a faster loop
 */
const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, '..', '..');
const catalogPath = join(repoRoot, 'tools', 'dspace', 'catalog.json');
const outputRoot = join(repoRoot, 'tools', 'dspace', 'saf');

const args = process.argv.slice(2);
const areaLimitFlag = args.indexOf('--areas');
const areaLimit =
  areaLimitFlag === -1
    ? Number.POSITIVE_INFINITY
    : Number(args[areaLimitFlag + 1]);

const catalog = JSON.parse(readFileSync(catalogPath, 'utf8'));
const areas = catalog.areas.slice(0, areaLimit);
const programs = catalog.programs.filter((program) => program.enabled);

/** XML text escaping. Source URLs carry query strings, so ampersands are not hypothetical. */
function escapeXml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function slug(value) {
  return value.toLowerCase().replaceAll(' ', '-');
}

function fill(template, tokens) {
  return String(template).replace(/\{(\w+)\}/g, (match, token) =>
    token in tokens ? String(tokens[token]) : match,
  );
}

function dcvalue(element, qualifier, value) {
  return `  <dcvalue element="${element}" qualifier="${qualifier}">${escapeXml(value)}</dcvalue>\n`;
}

function buildItem(program, area) {
  const tokens = {
    vintage: program.vintage,
    area: area ? area.name : (program.geography ?? 'United States'),
    areaSlug: area ? slug(area.name) : 'united-states',
    fips: area ? area.fips : '',
    abbreviation: area ? area.abbreviation : '',
    abbreviationLower: area ? area.abbreviation.toLowerCase() : '',
  };

  const sourceUrl = fill(program.sourceUrlTemplate, tokens);
  const documentationUrl = fill(program.documentationUrl, tokens);
  const withUrls = { ...tokens, sourceUrl, documentationUrl };

  return {
    id: fill(program.idTemplate, withUrls),
    title: fill(program.titleTemplate, withUrls),
    abstract: fill(program.abstractTemplate, withUrls),
    issued: fill(program.issuedTemplate, withUrls),
    citation: fill(program.citationTemplate, withUrls),
    geography: tokens.area,
    geographyLevel: program.geographyLevel,
    programId: program.id,
    vintage: String(program.vintage),
    publisher: catalog.publisherDefaults[program.publisher],
    subjects: program.subjects,
    sourceUrl,
    documentationUrl,
    files: program.files.map((file) => ({
      ...file,
      url: fill(file.url, withUrls),
    })),
  };
}

/**
 * Directories are named by source identifier, not by position.
 *
 * The seed's mapfile records "<directory> <handle>", and `dspace import --resume` skips directories
 * it has already imported. Positional names (item_000) would shift whenever the program mix or area
 * list changed, so a regeneration would silently re-import existing items under new handles and
 * leave two repository items claiming the same source identifier.
 */
function writeItem(item) {
  const directory = join(outputRoot, item.id);
  mkdirSync(directory, { recursive: true });

  let dublinCore = '<?xml version="1.0" encoding="UTF-8"?>\n';
  dublinCore +=
    '<!-- Generated by tools/scripts/generate-saf.mjs from tools/dspace/catalog.json. Do not edit. -->\n';
  dublinCore += '<dublin_core schema="dc">\n';
  dublinCore += dcvalue('title', 'none', item.title);
  dublinCore += dcvalue('contributor', 'author', item.publisher);
  dublinCore += dcvalue('publisher', 'none', item.publisher);
  dublinCore += dcvalue('description', 'abstract', item.abstract);
  dublinCore += dcvalue('date', 'issued', item.issued);
  dublinCore += dcvalue('identifier', 'other', item.id);
  dublinCore += dcvalue('identifier', 'uri', item.sourceUrl);
  dublinCore += dcvalue('relation', 'uri', item.documentationUrl);
  dublinCore += dcvalue('identifier', 'citation', item.citation);
  for (const subject of item.subjects) {
    dublinCore += dcvalue('subject', 'none', subject);
  }
  dublinCore += dcvalue('coverage', 'spatial', item.geography);
  dublinCore += '</dublin_core>\n';
  writeFileSync(join(directory, 'dublin_core.xml'), dublinCore, 'utf8');

  // Non-dc schemas live in their own file; DSpace ignores a per-value schema attribute.
  let crr = '<?xml version="1.0" encoding="UTF-8"?>\n';
  crr +=
    '<!-- Generated by tools/scripts/generate-saf.mjs. Fields registered in tools/dspace/crr-types.xml. -->\n';
  crr += '<dublin_core schema="crr">\n';
  crr += dcvalue('identifier', 'source', item.id);
  crr += dcvalue('program', 'none', item.programId);
  crr += dcvalue('geography', 'level', item.geographyLevel);
  crr += dcvalue('vintage', 'none', item.vintage);
  crr += dcvalue('source', 'url', item.sourceUrl);
  crr += dcvalue('documentation', 'url', item.documentationUrl);
  for (const file of item.files) {
    // Matches DspaceFileManifest.encode on the Java side, so a seeded item and a synchronized one
    // describe their files identically and sync:diff can reach SKIP_ITEM without a first apply.
    crr += dcvalue(
      'file',
      'manifest',
      JSON.stringify({
        id: file.id,
        label: file.label,
        bundle: 'ORIGINAL',
        format: file.format,
        url: file.url,
      }),
    );
  }
  crr += '</dublin_core>\n';
  writeFileSync(join(directory, 'metadata_crr.xml'), crr, 'utf8');

  writeFileSync(join(directory, 'contents'), '\n', 'utf8');
}

rmSync(outputRoot, { recursive: true, force: true });
mkdirSync(outputRoot, { recursive: true });

const items = [];
for (const program of programs) {
  if (program.scope === 'national') {
    items.push(buildItem(program, null));
    continue;
  }

  for (const area of areas) {
    items.push(buildItem(program, area));
  }
}

// Stable ordering keeps regeneration diff-free.
items.sort((left, right) => left.id.localeCompare(right.id));

const seen = new Set();
for (const item of items) {
  if (seen.has(item.id)) {
    throw new Error(
      `Duplicate source identifier in catalog output: ${item.id}`,
    );
  }
  seen.add(item.id);
  writeItem(item);
}

const byProgram = new Map();
for (const item of items) {
  byProgram.set(item.programId, (byProgram.get(item.programId) ?? 0) + 1);
}

console.log(`Generated ${items.length} SAF packages into tools/dspace/saf`);
for (const [programId, count] of [...byProgram].sort()) {
  console.log(`  ${programId.padEnd(12)} ${count}`);
}
if (Number.isFinite(areaLimit)) {
  console.log(`  (limited to the first ${areas.length} areas)`);
}
