import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const root = join(scriptDir, '..', '..');
const outputPath = join(root, 'documentation', 'platform-status.md');
const checkOnly = process.argv.includes('--check');

function readJson(...segments) {
  return JSON.parse(readFileSync(join(root, ...segments), 'utf8'));
}

function formatBytes(bytes) {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B';
  if (bytes >= 0.995 * 1024 ** 3)
    return `${(bytes / 1024 ** 3).toFixed(2)} GiB`;
  const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB'];
  const index = Math.min(
    Math.floor(Math.log(bytes) / Math.log(1024)),
    units.length - 1,
  );
  return `${(bytes / 1024 ** index).toFixed(index === 0 ? 0 : 2)} ${units[index]}`;
}

function countBy(values) {
  return values.reduce((counts, value) => {
    counts[value] = (counts[value] ?? 0) + 1;
    return counts;
  }, {});
}

const fixture = readJson(
  'apps',
  'repository-api',
  'src',
  'main',
  'resources',
  'discovery-fixture-catalog.json',
);
const inventory = readJson(
  'apps',
  'repository-api',
  'src',
  'main',
  'resources',
  'source-inventory.json',
);
const mirror = readJson('tools', 'dspace', 'mirror-manifest.json');
const evidence = readJson(
  'documentation',
  'accessibility-evidence',
  'automated-scans',
  'latest.json',
);

const adapterDirectory = join(
  root,
  'apps',
  'repository-api',
  'src',
  'main',
  'java',
  'org',
  'civicsrepo',
  'sources',
);
const adapterCount = readdirSync(adapterDirectory).filter(
  (name) =>
    name.endsWith('MetadataAdapter.java') &&
    ![
      'PublicMetadataAdapter.java',
      'CatalogBackedMetadataAdapter.java',
    ].includes(name),
).length;

const items = fixture.items ?? [];
const programCount = new Set(items.map((item) => item.program)).size;
const byType = countBy(items.map((item) => item.contentType ?? 'UNKNOWN'));
const typeRows = Object.entries(byType)
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([type, count]) => `| ${type} | ${count} |`)
  .join('\n');

// These are runtime-verification or delivered-surface facts rather than facts derived from the
// small curated catalog. Keep them here, in one place, instead of repeating divergent values
// across README, architecture, roadmap, and demo documents.
const runtimeFacts = {
  verifiedAt: '2026-08-20',
  dspaceIdentityCount: 176,
  curatedWithoutAdapterIdentity: 5,
  frontends: [
    {
      name: '`apps/discovery-ui`',
      port: '`4200`',
      role: 'Full discovery, research detail, Maps, Evidence, Search Lab and admin workflows',
    },
    {
      name: '`apps/census-mobile-frontend`',
      port: '`4300`',
      role: 'Mobile-first search, filters, ranking evidence and research-context journey',
    },
  ],
  mapLayers: [
    'TIGER/Line boundaries',
    'LODES workplace employment (WAC)',
    'LODES commuting flows (OD)',
    'SAIPE socioeconomic context',
    'Data.gov research extents',
    'Census Population Estimates (Vintage 2025)',
    'Census County Business Patterns (2023)',
    'USGS 3D Hydrography Program',
    'USGS earthquakes',
    'USGS 3DEP terrain/reference imagery',
  ],
};

const frontendRows = runtimeFacts.frontends
  .map(({ name, port, role }) => `| ${name} | ${port} | ${role} |`)
  .join('\n');

const markdown = `# Current Platform Status

> Generated by \`pnpm run docs:status\` from repository artifacts. Do not edit the generated facts by hand. Runtime-verification and delivered-surface facts that cannot be derived from the curated catalog are isolated in \`tools/scripts/platform-status.mjs\`.

## Product position

Civics Research Repository is an independent reference implementation of a federal Open Science repository and discovery platform. DSpace is the repository system of record; application-owned search projections power public discovery; two Angular frontends provide complementary full-workspace and mobile-first research experiences over the same typed Spring/OpenAPI boundary.

The platform is not affiliated with, endorsed by, or sponsored by the U.S. Census Bureau, USGS, DSpace, Apache Solr, Data.gov, DOE OSTI, or OpenSearch.

## Frontend surfaces

| Frontend | Development port | Current role |
| --- | --- | --- |
${frontendRows}

Both browser applications use the generated repository API client. Neither frontend calls DSpace, Solr, OpenSearch or external publishers directly.

The mobile-first surface now includes shareable query/filter intent, scalable cursor traversal, server-owned rank/relevance evidence, query-wide result summaries, typed field/term match evidence, authority-neutral research detail, research-package/related-research navigation and responsive browser/axe evidence. Shared rank/relevance presentation is consumed by both Angular applications through \`shared-ui\`.

## Repository breadth

| Measure | Current value |
| --- | ---: |
| Research objects | ${items.length} |
| Research programs | ${programCount} |
| Registered metadata adapters | ${adapterCount} |
| Objects with a recorded DSpace identity (runtime verified ${runtimeFacts.verifiedAt}) | ${runtimeFacts.dspaceIdentityCount} |
| Curated research-package objects intentionally without adapter identity | ${runtimeFacts.curatedWithoutAdapterIdentity} |

### Objects by type

| Type | Count |
| --- | ---: |
${typeRows}

The five curated objects are publications, methodology/project material, and restricted research metadata whose relationships are curatorial assertions rather than facts discovered from a publisher endpoint.

## Source and preservation snapshot

| Measure | Current value |
| --- | ---: |
| Source inventory checked | ${inventory.checkedAt} |
| Distinct referenced files | ${inventory.distinctFileCount} |
| Measured files | ${inventory.measuredFileCount} |
| Unreachable files at inventory time | ${inventory.unreachableFileCount} |
| Measured subscribed bytes | ${formatBytes(inventory.totalBytes)} |
| Mirrored files | ${mirror.mirroredFileCount} |
| Mirrored bytes | ${formatBytes(mirror.mirroredBytes)} |
| Mirror snapshot captured | ${mirror.mirroredAt} |

Mirroring is deliberately bounded. DSpace holds real bitstreams for eligible files inside the configured budget; remaining objects retain authoritative publisher links and file manifests.

## Discovery and synchronization

- DSpace owns repository items, metadata, relationships, access statements, versions, and bitstreams.
- Application PostgreSQL retains federated metadata, checkpoints, activation/evidence state and other application-owned operational data.
- The \`DiscoveryIndex\` boundary owns rebuildable public projections; Solr is the normal discovery engine and OpenSearch remains the aligned comparison target for controlled evidence.
- Fourteen registered Spring adapters reconcile catalog-backed \`ResearchObjectMetadata\` into DSpace. Startup and admin sync use the same orchestration path.
- Publisher checks provide reachable file facts and vintage verification, while the catalog remains a curated declaration of which research objects belong in this reference repository.
- Fixture content is a labelled recovery path, never an undisclosed substitute for repository content.

## Research/search evidence position

The certified standalone C2 baseline and adversarial C2.1 follow-up are complete and remain separately versioned evidence layers. The accepted million-record corpus/projection identities are historical/control evidence and are not rewritten by ordinary UI, Maps or dependency-maintenance work.

The project does not require another million-record run merely to prove the accepted baseline again.

## Geospatial and research-to-impact views

The current map workspace includes:

${runtimeFacts.mapLayers.map((layer) => `- ${layer}`).join('\n')}

The workforce journey connects discovery results to an area-focused view that combines workplace employment and commuting flows while retaining accessible table/list equivalents and synchronized selection state. New thematic layers continue to reuse authoritative geometry/value contracts and explicit nonvisual equivalents where the visual layer carries research meaning.

## Accessibility evidence

| Measure | Current value |
| --- | --- |
| Latest recorded automated evidence baseline | ${evidence.capturedAt} |
| Recorded commit | ${evidence.commit} |
| Component accessibility status | ${evidence.componentAccessibility?.status ?? 'UNKNOWN'} |
| Browser evidence status | ${evidence.e2eEvidence?.status ?? 'UNKNOWN'} |
| Forced-colors capability recorded | ${evidence.capabilities?.forcedColors ? 'Yes' : 'No'} |

Automated coverage includes template linting, component-state axe scans, browser axe scans, structural semantics, keyboard/focus preconditions, responsive/reflow evidence, contrast/forced-colors checks and equivalent nonvisual map data. Additional mobile browser evidence covers representative phone/tablet widths, research-detail navigation, reduced-motion behavior and search/filter focus behavior.

Manual keyboard/NVDA/JAWS/VoiceOver/cognitive evidence remains a separate evidence class and must not be inferred from automated passes. Manual assistive-technology execution is not part of the current completion path; the repository must not claim manual Section 508/Trusted Tester certification from automation.

## Deployment and governance

- Local Docker Compose is implemented and is the supported demonstration environment for both Angular frontends and the shared API/search stack.
- AWS modernization is documented; Terraform/CDK is not yet implemented.
- Dedicated browser evidence is implemented, while required-check and branch-protection policy remain governance decisions.
- Temporary transitive dependency overrides and accepted no-fix build-chain advisories are governed in \`planning/RISKS.md\`.

## Current continuation

The active product-facing sequence is:

1. #97 — shared result explainability dialog across both Angular frontends;
2. #98 — design lifecycle evidence for a representative mobile-first slice;
3. #99 — read-only repository steward/status workflow.

Additional federation, Maps breadth, clustered topology and cloud deployment remain optional until a concrete research or deployment question justifies them.

## Refresh commands

\`pnpm run docs:status\` regenerates this document.  
\`pnpm run docs:check\` fails when the committed status no longer matches its source artifacts.  
\`pnpm run evidence:refresh\` records a new automated accessibility baseline only after the configured automated suites pass.
`;

const normalized = await prettier.format(`${markdown.trim()}\n`, {
  parser: 'markdown',
});
if (checkOnly) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== normalized) {
    console.error(
      'documentation/platform-status.md is stale. Run: pnpm run docs:status',
    );
    process.exit(1);
  }
  console.log(
    'documentation/platform-status.md matches current repository artifacts.',
  );
} else {
  writeFileSync(outputPath, normalized, 'utf8');
  console.log('Updated documentation/platform-status.md');
}
