import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const root = join(scriptDir, '..', '..');
const outputPath = join(root, 'documentation', 'platform-status.md');
const checkOnly = process.argv.includes('--check');

function readJson(...segments) {
  return JSON.parse(readFileSync(join(root, ...segments), 'utf8'));
}

function formatBytes(bytes) {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B';
  if (bytes >= 0.995 * 1024 ** 3)
    return `${(bytes / 1024 ** 3).toFixed(2)} GiB`;
  const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB'];
  const index = Math.min(
    Math.floor(Math.log(bytes) / Math.log(1024)),
    units.length - 1,
  );
  return `${(bytes / 1024 ** index).toFixed(index === 0 ? 0 : 2)} ${units[index]}`;
}

function countBy(values) {
  return values.reduce((counts, value) => {
    counts[value] = (counts[value] ?? 0) + 1;
    return counts;
  }, {});
}

const fixture = readJson(
  'apps',
  'repository-api',
  'src',
  'main',
  'resources',
  'discovery-fixture-catalog.json',
);
const inventory = readJson(
  'apps',
  'repository-api',
  'src',
  'main',
  'resources',
  'source-inventory.json',
);
const mirror = readJson('tools', 'dspace', 'mirror-manifest.json');
const evidence = readJson(
  'documentation',
  'accessibility-evidence',
  'automated-scans',
  'latest.json',
);

const adapterDirectory = join(
  root,
  'apps',
  'repository-api',
  'src',
  'main',
  'java',
  'org',
  'civicsrepo',
  'sources',
);
const adapterCount = readdirSync(adapterDirectory).filter(
  (name) =>
    name.endsWith('MetadataAdapter.java') &&
    ![
      'PublicMetadataAdapter.java',
      'CatalogBackedMetadataAdapter.java',
    ].includes(name),
).length;

const items = fixture.items ?? [];
const programCount = new Set(items.map((item) => item.program)).size;
const byType = countBy(items.map((item) => item.contentType ?? 'UNKNOWN'));
const typeRows = Object.entries(byType)
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([type, count]) => `| ${type} | ${count} |`)
  .join('\n');

// These are runtime-verification facts rather than catalog-derived facts. Keep them here, in one
// place, instead of repeating them across README, architecture, roadmap, and demo documents.
const runtimeFacts = {
  verifiedAt: '2026-08-20',
  dspaceIdentityCount: 176,
  curatedWithoutAdapterIdentity: 5,
  mapLayers: [
    'TIGER/Line boundaries',
    'LODES workplace employment (WAC)',
    'LODES commuting flows (OD)',
    'SAIPE socioeconomic context',
    'USGS 3D Hydrography Program',
    'USGS earthquakes',
  ],
};

const markdown = `# Current Platform Status

> Generated by \`pnpm run docs:status\` from repository artifacts. Do not edit the generated facts by hand. Runtime-verification facts that cannot be derived from committed artifacts are isolated in \`tools/scripts/platform-status.mjs\`.

## Product position

Civics Research Repository is an independent reference implementation of a federal Open Science repository and discovery platform. DSpace is the repository system of record; an application-owned discovery index powers public search; Angular and MapLibre provide an accessible discovery, research-object, workflow, and geospatial experience.

The platform is not affiliated with, endorsed by, or sponsored by the U.S. Census Bureau, USGS, DSpace, or Apache Solr.

## Repository breadth

| Measure | Current value |
| --- | ---: |
| Research objects | ${items.length} |
| Research programs | ${programCount} |
| Registered metadata adapters | ${adapterCount} |
| Objects with a recorded DSpace identity (runtime verified ${runtimeFacts.verifiedAt}) | ${runtimeFacts.dspaceIdentityCount} |
| Curated research-package objects intentionally without adapter identity | ${runtimeFacts.curatedWithoutAdapterIdentity} |

### Objects by type

| Type | Count |
| --- | ---: |
${typeRows}

The five curated objects are publications, methodology/project material, and restricted research metadata whose relationships are curatorial assertions rather than facts discovered from a publisher endpoint.

## Source and preservation snapshot

| Measure | Current value |
| --- | ---: |
| Source inventory checked | ${inventory.checkedAt} |
| Distinct referenced files | ${inventory.distinctFileCount} |
| Measured files | ${inventory.measuredFileCount} |
| Unreachable files at inventory time | ${inventory.unreachableFileCount} |
| Measured subscribed bytes | ${formatBytes(inventory.totalBytes)} |
| Mirrored files | ${mirror.mirroredFileCount} |
| Mirrored bytes | ${formatBytes(mirror.mirroredBytes)} |
| Mirror snapshot captured | ${mirror.mirroredAt} |

Mirroring is deliberately bounded. DSpace holds real bitstreams for eligible files inside the configured budget; remaining objects retain authoritative publisher links and file manifests.

## Discovery and synchronization

- DSpace owns repository items, metadata, relationships, access statements, versions, and bitstreams.
- The \`DiscoveryIndex\` boundary owns a rebuildable public projection; Apache Solr is the current implementation.
- Fourteen registered Spring adapters reconcile catalog-backed \`ResearchObjectMetadata\` into DSpace. Startup and admin sync use the same orchestration path.
- Publisher checks provide reachable file facts and vintage verification, while the catalog remains a curated declaration of which research objects belong in this reference repository.
- Fixture content is a labelled recovery path, never an undisclosed substitute for repository content.

## Geospatial and research-to-impact views

The current map workspace includes:

${runtimeFacts.mapLayers.map((layer) => `- ${layer}`).join('\n')}

The workforce journey connects discovery results to an area-focused view that combines workplace employment and commuting flows while retaining accessible table/list equivalents and synchronized selection state.

## Accessibility evidence

| Measure | Current value |
| --- | --- |
| Latest recorded automated evidence | ${evidence.capturedAt} |
| Recorded commit | ${evidence.commit} |
| Component accessibility status | ${evidence.componentAccessibility?.status ?? 'UNKNOWN'} |
| Browser evidence status | ${evidence.e2eEvidence?.status ?? 'UNKNOWN'} |
| Forced-colors capability recorded | ${evidence.capabilities?.forcedColors ? 'Yes' : 'No'} |

Automated coverage includes template linting, component-state axe scans, browser axe scans, structural semantics, keyboard preconditions, reflow, zoom, contrast, forced colors, dark mode, and equivalent nonvisual map data. Manual keyboard, NVDA, JAWS, map-equivalence, and cognitive evidence remain separate and must not be inferred from automated passes.

## Deployment and governance

- Local Docker Compose is implemented and is the supported demonstration environment.
- AWS modernization is documented; Terraform/CDK is not yet implemented.
- The main CI workflow does not yet enforce the full browser accessibility matrix.
- Branch protection and required checks remain governance decisions.

## Refresh commands

\`pnpm run docs:status\` regenerates this document.  
\`pnpm run docs:check\` fails when the committed status no longer matches its source artifacts.  
\`pnpm run evidence:refresh\` records a new accessibility baseline only after all automated suites pass.
`;

const normalized = `${markdown.trim()}\n`;
if (checkOnly) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== normalized) {
    console.error(
      'documentation/platform-status.md is stale. Run: pnpm run docs:status',
    );
    process.exit(1);
  }
  console.log(
    'documentation/platform-status.md matches current repository artifacts.',
  );
} else {
  writeFileSync(outputPath, normalized, 'utf8');
  console.log('Updated documentation/platform-status.md');
}
